export const SET_DIRTY = "SET_DIRTY"
export const SET_FIELD_VALUE = "SET_FIELD_VALUE"
export const SET_FIELD_TOUCHED = "SET_FIELD_TOUCHED"
export const SET_ERRORS = "SET_ERRORS"
export const SET_VALUES = "SET_VALUES"
export const SET_RESET = "SET_RESET"
export const SET_TOUCHED = "SET_TOUCHED"